# Generated by Django 4.2.11 on 2024-07-03 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Combustibles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_combustible', models.CharField(choices=[('G93', 'Gasolina 93 Octanos'), ('G95', 'Gasolina 95 Octanos'), ('G97', 'Gasolina 97 Octanos'), ('DIE', 'Diesel convencional'), ('DIP', 'Diesel de alto rendimiento'), ('JA1', 'Jet A-1'), ('AVG', 'Av Gas')], max_length=4)),
                ('nombre_combustible', models.CharField(max_length=60)),
                ('zona_produccion', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Plantas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_planta', models.CharField(max_length=4)),
                ('nombre_planta', models.CharField(max_length=100)),
            ],
        ),
    ]
