# Generated by Django 4.2.11 on 2024-07-03 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_combustibles_plantas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combustibles',
            name='zona_produccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.plantas'),
        ),
    ]
