# Generated by Django 4.2.11 on 2024-07-03 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_combustibles_zona_produccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combustibles',
            name='codigo_combustible',
            field=models.CharField(max_length=4),
        ),
    ]
