# Generated by Django 4.2.11 on 2024-07-03 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_combustibles_codigo_combustible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroproduccion',
            name='codigo_combustible',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.combustibles'),
        ),
    ]
